form_history:
  branch:
  - Piotr/verifying-control-algorihtms
  git_url:
  - ssh://git@ben.ii.pw.edu.pl:9000/pwalas/swarm-gym.git
  job:
  - batch_example/job.sh
  ssh:
  - hpc
query_interval: 10
ssh_hosts:
- hpc
